# Generated by Django 3.0.8 on 2020-08-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20200817_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_stock',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
    ]
