# Generated by Django 3.0.8 on 2020-08-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_product_total_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
